---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-a-vault-agent-config
  namespace: project-demo
data:
  vault-agent-config.hcl: |
    # Comment this out if running as sidecar instead of initContainer
    exit_after_auth = true

    pid_file = "/home/vault/pidfile"

    auto_auth {
        method "jwt" {
            mount_path = "auth/jwt-demo"
            config = {
              path = "/var/run/secrets/tokens/vault"
              role = "demo-dev-service-a"
            }
        }

        sink "file" {
            config = {
                path = "/vault/token"
            }
        }
    }

    template {
      destination = "/etc/secrets/secret.json"
      contents = <<EOT
      {{- with secret "secret-demo/data/demo/dev/secret_service_a" }}
      {{ .Data.data  | toJSONPretty }}
      {{ end }}
      EOT
    }

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-a
  namespace: project-demo
---
apiVersion: v1
kind: Pod
metadata:
  name: service-a
  namespace: project-demo
spec:
  serviceAccountName: service-a
  initContainers:
    - args:
        - agent
        - -config=/etc/vault/vault-agent-config.hcl
        - -log-level=debug
      env:
        - name: VAULT_ADDR
          value: "https://vault.dtsdemo.com"
      image: vault:1.13.3
      name: vault-agent
      volumeMounts:
        - mountPath: /etc/vault
          name: config
        - mountPath: /etc/secrets
          name: shared-data
        - mountPath: /var/run/secrets/tokens
          name: vault-token

  containers:
    - name: nginx
      image: nginx:stable-alpine
      volumeMounts:
        - mountPath: /secrets
          name: shared-data
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  volumes:
    - name: vault-token
      projected:
        sources:
          - serviceAccountToken:
              path: vault
              audience: vault
              expirationSeconds: 600
    - configMap:
        items:
          - key: vault-agent-config.hcl
            path: vault-agent-config.hcl
        name: service-a-vault-agent-config
      name: config
    - emptyDir: {}
      name: shared-data
