---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-b
  namespace: project-demo
---
apiVersion: v1
kind: Pod
metadata:
  name: service-b
  namespace: project-demo
spec:
  serviceAccountName: service-b
  containers:
    - name: nginx
      image: nginx
