---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-b
  namespace: project-demo
---
apiVersion: v1
kind: Pod
metadata:
  name: service-b
  namespace: project-demo
spec:
  serviceAccountName: service-b
  containers:
    - name: nginx
      image: alpine/curl
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      command: ["sh","-c","apk add grep;sleep 100000000"]
