---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-a
  namespace: project-demo
---
apiVersion: v1
kind: Pod
metadata:
  name: service-a
  namespace: project-demo
spec:
  serviceAccountName: service-a
  containers:
    - name: nginx
      image: nginx:stable-alpine
      volumeMounts:
        - mountPath: /var/run/secrets/tokens
          name: vault-token
  volumes:
    - name: vault-token
      projected:
        sources:
          - serviceAccountToken:
              path: vault
              audience: vault
              expirationSeconds: 600